In [29]:
import pandas as pd
import numpy as np

### Pandas is a Python library used for:

- Data cleaning
- Data analysis
- Data manipulation
- Working with tabular data

In [5]:
s=pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [9]:
s.name="calaroies"
s

0    10
1    20
2    30
3    40
Name: calaroies, dtype: int64

In [12]:
print(s[0])

10

In [14]:
print(s[3])

40

In [15]:
s1=pd.Series([10,20,30,40], index=["A","B","C","D"])
s1

A    10
B    20
C    30
D    40
dtype: int64

In [19]:
s1['B']

np.int64(20)

In [20]:
s1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [21]:
s1.values

array([10, 20, 30, 40])

In [22]:
s1.shape

(4,)

In [24]:
s.dtype

dtype('int64')

In [30]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [31]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [34]:
df.head()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN

In [35]:
df.tail()

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [37]:
df.iloc[1:3,:3]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance

In [39]:
df[['Age','Department']]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [41]:
df.shape

(6, 4)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [43]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [46]:
# Broadcasting

df["Salary"] = df["Salary"] + 500
df["Salary"]

0    60500.0
1    70500.0
2    80500.0
3    72500.0
4        NaN
5    60500.0
Name: Salary, dtype: float64